# Generated by Django 5.0.2 on 2024-03-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_ticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='zip_code',
            new_name='zipCode',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='compensationAsOfEpochDate',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='dateShortInterest',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='exDividendDate',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='governanceEpochDate',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='lastDividendDate',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='lastFiscalYearEnd',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='lastSplitDate',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='mostRecentQuarter',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='nextFiscalYearEnd',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='sharesShortPreviousMonthDate',
        ),
    ]
