# Generated by Django 5.0.2 on 2024-03-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_ticker_sharesshortpreviousmonthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='compensationAsOfEpochDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='dateShortInterest',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='exDividendDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='governanceEpochDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='lastDividendDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='lastFiscalYearEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='lastSplitDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='mostRecentQuarter',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='nextFiscalYearEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
