# Generated by Django 5.0.2 on 2024-03-03 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_ticker_compensationasofepochdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='sectorDisp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='sectorKey',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='appSector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.sector'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
