# Generated by Django 5.0.2 on 2024-03-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_sector_sectordisp_sector_sectorkey_ticker_appsector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='industryDisp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='industryKey',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
