# Generated by Django 5.0.2 on 2024-03-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_industry_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='postMarket',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='preMarket',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
