# Generated by Django 5.0.2 on 2024-03-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_ticker_postmarket_ticker_premarket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
