# Generated by Django 5.0.2 on 2024-03-17 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_stockprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ticker'),
        ),
    ]
